### ISSUE TITLE
Feature Request: Drag-and-drop / Paste from Clipboard

### ISSUE THREAD

**Issue by Xectali** [lfiore/upld#11]
It will be good if you can add way of drag-and-drop or paste from clipboard.

**Comment by Barrnet** [comment]
> 
> 
> It will be good if you can add way of drag-and-drop or paste from clipboard.

Add this on top of "js/upload.js" file:
`const fileInput = document.getElementById("image-input");
window.addEventListener('paste', e => {
 fileInput.files = e.clipboardData.files;
$('#upload-form').submit();
});
`

**Comment by Xectali** [comment]
Thank you very much :)

**Comment by lfiore** [comment]
Barrnet's improvement has been added
