### ISSUE TITLE
possible to add extention

### ISSUE THREAD

**Issue by Samanw** [lfiore/upld#2]
is there a option to add extension like .zip for upload?

**Comment by lfiore** [comment]
Do you mean allow .zip files to be uploaded and download, or allow users to upload image files stored in .zip files which are then unzipped on the server?

**Comment by Samanw** [comment]
users allow to upload zip files and script generate a download link for that files,
thx for answering and your script

**Comment by lfiore** [comment]
Unfortunately I wrote the script to not allow direct file downloads on purpose (to limit who can download them or password protect them).

There should be plenty of other scripts on Github which allow file uploads with direct links but I don't know any of the top of my head.

Thanks for the feedback anyway, I may consider updating it and adding this is a feature, but it's unlikely.

**Comment by Samanw** [comment]
well it will be very good if u made a option in admin panel to change it

**Comment by inebunit** [comment]
what admin panel?
