### ISSUE TITLE
Add CSRF protection for actions

### ISSUE THREAD

**Issue by JixunMoe** [lfiore/upld#8]
e.g. ban feature did not use CSRF token to protect.

I can construct the url `http://somewhere.com/ban.php?id=1` and embed it as an image. Once an admin is tricked to visit the page, it will cause the server to begin deleting someone's images.

Suggestion: any action to be performed other than read should be verified against a valid CSRF token.

More details:

https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)

**Comment by lfiore** [comment]
added. thanks for the report
